name: linux-test

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: package install
      run: |
        mv ./linux/rclone ./pyrclone/rclone
    - name: Install dependencies
      run: |
        pip install . -v
        pip install pytest
    - name: Update permissions
      run: |
        sudo chmod 755 /opt/hostedtoolcache/Python/3.10.12/x64/pyrclone/rclone
    - name: Test with pytest
      run: |
        make test