name: Build and Publish Packages

on:
  push:
    branches:
      - main

jobs:
  build_and_publish_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: package install
      run: |
        mv linux/rclone pyrclone/rclone
    - name: Update permissions
      run: |
        sudo chmod 755 pyrclone/rclone
    - name: Install dependencies
      run: |
        pip install . -v

    - name: Test with pytest
      run: |
        make test
















    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: package install
      #   run: |
      #     mv mac/rclone pyrclone/rclone
      # - name: add permissions
      #   run: |
      #     chmod +x pyrclone/rclone

      # - name: Build and package for Mac
      #   run: |
      #     python setup.py bdist_wheel --plat-name macosx_10_15_x86_64

      # - name: Build and package for Windows
      #   run: |
      #     python setup.py bdist_wheel --plat-name win_amd64

      # - name: Build and package for Linux
      #   run: |
      #     python setup.py bdist_wheel --plat-name manylinux1_x86_64

      # - name: Merge and publish
      #   run: |
      #     mkdir merged_whl
      #     cp dist/*macosx_10_15_x86_64.whl merged_whl/
      #     cp dist/*win_amd64.whl merged_whl/
      #     cp dist/*manylinux1_x86_64.whl merged_whl/
      #     twine upload merged_whl/*
