name: Build and Publish Packages

on:
  push:


jobs:
  build_and_publish_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Dependencies
      run: |
        pip install wheel
    - name: Add Rclone Binary File
      run: |
        mv linux/rclone pyrclone/rclone
    - name: Update Permissions
      run: |
        sudo chmod 755 pyrclone/rclone
    - name: Build And Package for Linux
      run: |
        make package OS="manylinux1_x86_64"
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}


  build_and_publish_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Dependencies
      run: |
        pip install wheel
    - name: Add Rclone Binary File
      run: |
        move win/rclone.exe pyrclone/rclone.exe
    - name: Build And Package for Windows
      run: |
        make package OS="win_amd64"
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

  build_and_publish_mac:
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Dependencies
        run: |
          pip install wheel
      - name: Add Rclone Binary File
        run: |
          mv mac/rclone pyrclone/rclone
      - name: Update Permissions
        run: |
          sudo chmod 755 pyrclone/rclone
      - name: Build And Package for Mac
        run: |
          make package OS="macosx_10_9_x86_64"
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

